% MAIN_RANGE_PROFILE  距离历程图（HRRP历程图）计算程序
%
%   High Resolution Range Profile (HRRP) Map Generation
%   一维距离像历程图生成程序
%
%   根据"距离历程计算方法.txt"第3-6节的流程：
%     1. 加载宽带复散射场数据 S_complex(theta, f)
%     2. 对每个观测角度下的宽带频域序列依次执行：
%        a) 频域加权（窗函数，抑制距离旁瓣）
%        b) 补零（增大 IFFT 点数，使距离轴更平滑）
%        c) 逆傅里叶变换 IFFT -> 复数距离剖面 h(r)
%        d) 取模并转换为 dB：HRRP(r) = 20*log10(|h(r)| + epsilon)
%        e) 距离轴标定：r_k = k * c/(2B) * (N_f / N_fft)
%     3. 将所有角度的距离像拼接为二维矩阵 M (N_theta x N_fft)
%     4. 绘制二维彩色历程图：
%        - 横轴：径向距离（米）
%        - 纵轴：观测角度（度）
%        - 颜色：散射强度（dB）
%     5. 额外诊断图：原始频域散射场热力图 + 单角度一维距离像
%
%   输入文件:
%     results/wideband_scattering_<timestamp>.mat  (由 main_wideband_scattering 生成)
%
%   Usage:
%     >> main_range_profile              % 自动查找最新结果文件
%     >> main_range_profile('file.mat')  % 指定结果文件

function main_range_profile(varargin)

% 解析输入参数：若未指定文件，自动查找 results/ 下最新的
if nargin < 1 || isempty(varargin{1})
    resultFile = '';  % 触发自动查找
else
    resultFile = varargin{1};
end

if isempty(resultFile)
    resultDir = fullfile('results');
    files = dir(fullfile(resultDir, 'wideband_scattering_*.mat'));
    if isempty(files)
        error('main_range_profile:NoDataFile', ...
              'No wideband_scattering_*.mat found in %s.\nRun main_wideband_scattering first.', resultDir);
    end
    [~, idx] = sort([files.datenum], 'descend');
    resultFile = fullfile(resultDir, files(idx(1)).name);
    fprintf('Auto-selected: %s\n', resultFile);
end

fprintf('\n========================================\n');
fprintf('  Range Profile Map Generation\n');
fprintf('  (距离历程图生成)\n');
fprintf('========================================\n\n');

%% ========================================================================
%% 1. 加载宽带复散射场数据
%% ========================================================================
fprintf('Loading wideband scattering data...\n');

if ~exist(resultFile, 'file')
    error('main_range_profile:FileNotFound', 'File not found: %s', resultFile);
end

data = load(resultFile);

% 验证必要字段 — 区分 wideband_scattering (输入) vs range_profile_data (输出)
requiredFields = {'S_complex', 'freq_array', 'phi_array', 'theta_array', ...
                  'c', 'B', 'delta_r', 'ip', 'it', 'N_f', 'N_angles_total'};
missingFields = {};
for k = 1:length(requiredFields)
    if ~isfield(data, requiredFields{k})
        missingFields{end+1} = requiredFields{k}; %#ok<AGROW>
    end
end
if ~isempty(missingFields)
    % 检测是否误加载了 range_profile_data_*.mat (输出文件)
    if isfield(data, 'M_dB') && isfield(data, 'range_axis')
        error('main_range_profile:WrongFileType', ...
              ['This appears to be a range_profile_data file (output), ' ...
               'not a wideband_scattering file (input).\n' ...
               'Please use a wideband_scattering_*.mat file generated by main_wideband_scattering.\n' ...
               'Or simply run: main_range_profile (no arguments) to auto-select.']);
    else
        error('main_range_profile:MissingField', ...
              'Missing required field(s): %s.\nThis file may not be a valid wideband_scattering result.', ...
              strjoin(missingFields, ', '));
    end
end

S_complex      = data.S_complex;       % 复散射场矩阵 (N_angles x N_f)
freq_array     = data.freq_array;      % 频率数组 (Hz)
phi_array      = data.phi_array;       % phi 角度数组 (ip x it)
theta_array    = data.theta_array;     % theta 角度数组 (ip x it)
c              = data.c;               % 光速
B              = data.B;               % 带宽 (Hz)
delta_r        = data.delta_r;         % 距离分辨率 (m)
ip             = data.ip;              % phi 步数
it             = data.it;              % theta 步数
N_f            = data.N_f;             % 频点数
N_angles_total = data.N_angles_total;  % 总角度数
ntria          = data.ntria;           % 三角面元数

% 模型名称（兼容旧版本数据文件）
if isfield(data, 'inputModel')
    [~, modelName, ~] = fileparts(data.inputModel);
else
    modelName = 'Unknown';
end

% 角度步长与范围（兼容旧版本）
delp = 0; delt = 0;
tstart = 0; tstop = 180; pstart = 0; pstop = 0;
if isfield(data, 'delp'),   delp   = data.delp;   end
if isfield(data, 'delt'),   delt   = data.delt;   end
if isfield(data, 'tstart'), tstart = data.tstart; end
if isfield(data, 'tstop'),  tstop  = data.tstop;  end
if isfield(data, 'pstart'), pstart = data.pstart; end
if isfield(data, 'pstop'),  pstop  = data.pstop;  end

fprintf('  Data file: %s\n', resultFile);
fprintf('  Matrix size: %d angles x %d frequencies\n', N_angles_total, N_f);
fprintf('  Bandwidth: %.2f GHz\n', B/1e9);
fprintf('  Range resolution: %.4f m\n', delta_r);

%% ========================================================================
%% 2. 配置处理参数
%% ========================================================================
fprintf('\nConfiguring HRRP processing parameters...\n');

% ---- 2a. 窗函数选择 ----
% 支持: 'hamming', 'hanning', 'blackman', 'kaiser', 'none'
windowType = 'hamming';
fprintf('  Window function: %s\n', windowType);

switch lower(windowType)
    case 'hamming'
        W_freq = hamming(N_f)';
    case 'hanning'
        W_freq = hanning(N_f)';
    case 'blackman'
        W_freq = blackman(N_f)';
    case 'kaiser'
        W_freq = kaiser(N_f, 2.5)';
    case 'none'
        W_freq = ones(1, N_f);
    otherwise
        warning('Unknown window type "%s", using Hamming.', windowType);
        W_freq = hamming(N_f)';
end
W_freq = W_freq(:)';  % 确保为行向量

% ---- 2b. 补零因子 ----
zero_pad_factor = 4;
N_fft = N_f * zero_pad_factor;
if mod(N_fft, 2) ~= 0
    N_fft = N_fft + 1;
end
fprintf('  FFT points: %d (zero-pad factor: %dx)\n', N_fft, zero_pad_factor);

% ---- 2c. 相位参考中心对齐 ----
% 文献要求以质心为相位参考。对复杂多面体用包围盒中心近似。
% 方法：在频域乘相位斜坡 exp(-j*4πf/c * r0·k_hat)，等价于将参考点从
% 坐标原点移到 r0。不需修改几何坐标，也不用重新运行散射计算。
align_to_center = true;          % true: 将参考点移到包围盒中心
reference_point = [];            % 留空=自动用包围盒中心; 或指定 [x0,y0,z0] (m)
if align_to_center
    fprintf('  Phase reference: will align to bounding-box center (phase-ramp method)\n');
end

% ---- 2d. 归一化与动态范围 ----
% 由于 PO 面元法的 far-field 散射场幅值天然很小（|sumt| ~ 1e-3 量级），
% 经 IFFT 后 dB 值通常落在 -100 ~ -60 dB 范围。
% 归一化模式:
%   'global'    - 全局最大值归一 (0dB=最强散射, 保留角度间RCS差异) [推荐]
%   'per-angle' - 逐角度归一 (每角度独立峰值, 只看距离结构)
%   'none'      - 绝对dB值 (用于定量分析)
normalize_mode = 'global';     % 'global' | 'per-angle' | 'none'
auto_dyn_range = true;         % true: 自动计算显示范围; false: 手动指定
dyn_range_min = -60;           % 手动模式下的 dB 下限
dyn_range_max = 0;             % 手动模式下的 dB 上限
dyn_range_span = 150;           % 自动模式: 显示峰值以下多少 dB
epsilon_dB = 1e-10;
fprintf('  Normalization: %s\n', normalize_mode);

%% ========================================================================
%% 3. 对每个角度生成一维距离像 (核心计算)
%% ========================================================================
fprintf('\n========================================\n');
fprintf('  Computing Range Profiles (IFFT per angle)\n');
fprintf('========================================\n');
tic;

% 预分配: M_dB (N_angles x N_fft, dB 单位)
M_dB = zeros(N_angles_total, N_fft);

% Phase reference alignment setup (bbox center, robust for any polyhedron)
if align_to_center
    if isempty(reference_point)
        if isfield(data, 'bbox_center')
            reference_point = data.bbox_center;
            fprintf('  Using bbox center from data: [%.3f, %.3f, %.3f] m\n', reference_point);
        elseif isfield(data, 'inputModel')
            % Fallback: read STL model and compute bounding box
            modelFile = fullfile('stl_models', data.inputModel);
            if exist(modelFile, 'file')
                stlConverter(modelFile);
                coordData = extractCoordinatesData(0);
                xx = coordData{1}; yy = coordData{2}; zz = coordData{3};
                reference_point = [(min(xx)+max(xx))/2, (min(yy)+max(yy))/2, (min(zz)+max(zz))/2];
                fprintf('  Computed bbox center from model: [%.3f, %.3f, %.3f] m\n', reference_point);
            else
                reference_point = [0, 0, 0];
                fprintf('  Warning: model not found, using origin.\n');
            end
        else
            reference_point = [0, 0, 0];
            fprintf('  Warning: no bbox info, using origin (no correction).\n');
        end
    end
    r0 = reference_point(:);
end

for i_angle = 1:N_angles_total

    % ---- 3a. Extract wideband complex scattering for this angle ----
    Es_f = S_complex(i_angle, :);  % 1 x N_f

    % ---- 3a2. Phase-reference alignment (phase-ramp method) ----
    if align_to_center && norm(r0) > 1e-10
        % Determine current observation angle
        if ip > 1 && it == 1
            theta_i = pstart + (i_angle - 1) * delp;
        elseif it > 1 && ip == 1
            theta_i = tstart + (i_angle - 1) * delt;
        else
            i2 = mod(i_angle - 1, it) + 1;
            theta_i = tstart + (i2 - 1) * delt;
        end
        Es_f = alignPhaseReference(Es_f, freq_array, theta_i, 0, r0, c);
    end

    % ---- 3b. Apply frequency-domain window ----
    Es_windowed = W_freq .* Es_f;

    % ---- 3c. 补零 ----
    Es_padded = [Es_windowed, zeros(1, N_fft - N_f)];

    % ---- 3d. 逆傅里叶变换 (IFFT) ----
    h_complex = ifft(Es_padded, N_fft);

    % ---- 3e. ifftshift 使零距离在中心 ----
    % 参考 yw.m: ifftshift(ifft(...))
    % ifftshift 将 IFFT 结果中的零距离分量移到数组中心
    h_complex = ifftshift(h_complex);

    % ---- 3f. 取模并转换为 dB ----
    h_mag = abs(h_complex);
    M_dB(i_angle, :) = 20 * log10(h_mag + epsilon_dB);

end

% ---- 3g. 归一化 ----
switch normalize_mode
    case 'global'
        % 全局最大值归一: 0dB = 所有角度/距离中的最强散射
        % 保留角度间的 RCS 差异 → 强散射角度出现垂直峰值线
        global_peak = max(M_dB(:));
        M_dB = M_dB - global_peak;
        fprintf('  Global normalization: peak=%.1f dB, span preserved.\n', global_peak);
    case 'per-angle'
        % 逐角度归一: 每帧独立峰值 → 隐藏角度间差异，只看距离结构
        angle_peaks = max(M_dB, [], 2);
        M_dB = M_dB - angle_peaks;
        fprintf('  Per-angle normalization applied.\n');
    case 'none'
        % 不归一化，保留绝对 dB 值
        fprintf('  No normalization (absolute dB).\n');
end

elapsed = toc;
fprintf('Range profile computation: %.2f s (%.3f s/angle)\n', ...
    elapsed, elapsed / N_angles_total);

%% ========================================================================
%% 4. 距离轴标定
%% ========================================================================
fprintf('\nCalibrating range axis...\n');

% 距离单元间距 = c/(2B) * (N_f/N_fft)
delta_r_fft = delta_r * (N_f / N_fft);
% 最大不模糊距离 (由频率步长决定)
R_max = c / (2 * (freq_array(2) - freq_array(1)));

% 经 ifftshift 后零距离在中心: [-N_fft/2, N_fft/2-1] * delta_r_fft
range_axis = (-floor(N_fft/2) : floor(N_fft/2)-1) * delta_r_fft;

fprintf('  Range bin spacing: %.4f m (after zero-padding)\n', delta_r_fft);
fprintf('  Max unambiguous range: %.2f m\n', R_max);
fprintf('  Range axis: %.2f ~ %.2f m (%d bins)\n', ...
    range_axis(1), range_axis(end), N_fft);

%% ========================================================================
%% 5. 构建角度轴
%% ========================================================================
if ip > 1 && it == 1
    % 纯 phi 扫描
    angle_axis = phi_array(:, 1);
    angleLabel = 'Azimuth Angle \phi (deg)';
    angleStep = delp;
    angleStepLabel = '\Delta\phi';
elseif it > 1 && ip == 1
    % 纯 theta 扫描
    angle_axis = theta_array(1, :)';
    angleLabel = 'Elevation Angle \theta (deg)';
    angleStep = delt;
    angleStepLabel = '\Delta\theta';
else
    % 二维角度扫描
    angle_axis = (1:N_angles_total)';
    angleLabel = 'Observation Angle Index';
    angleStep = max(delp, delt);
    angleStepLabel = '\Delta\theta/\phi';
    fprintf('  Note: 2D angle scan detected. Using angle index for display.\n');
end

%% ========================================================================
%% 6. 图1: 距离历程图 (主图)
%% ========================================================================
fprintf('\nGenerating range profile map (Figure 1)...\n');

figure(1);
clf;
set(gcf, 'Name', 'Range Profile Map (距离历程图)', ...
         'NumberTitle', 'off', 'Position', [50, 100, 900, 650]);

% 自动或手动确定动态范围
if auto_dyn_range
    noise_floor = prctile(M_dB(:), 2);
    signal_peak = max(M_dB(:));
    if strcmp(normalize_mode, 'none')
        dyn_range_min = noise_floor;
        dyn_range_max = signal_peak;
    else
        % 归一化后 signal_peak=0，取峰值以下 dyn_range_span dB 为下限
        dyn_range_min = max(noise_floor, signal_peak - dyn_range_span);
        dyn_range_max = signal_peak;
    end
    fprintf('  Auto dynamic range: %.0f ~ %.0f dB\n', dyn_range_min, dyn_range_max);
else
    fprintf('  Manual dynamic range: %.0f ~ %.0f dB\n', dyn_range_min, dyn_range_max);
end

% 裁剪动态范围
M_display = M_dB;
M_display(M_display < dyn_range_min) = dyn_range_min;
M_display(M_display > dyn_range_max) = dyn_range_max;

imagesc(angle_axis, range_axis, M_display');
colormap('jet');
axis xy;

xlabel(angleLabel, 'FontSize', 12, 'FontWeight', 'bold');
ylabel('Radial Range (m)', 'FontSize', 12, 'FontWeight', 'bold');

% 构建标题字符串
normStr = ['Norm: ' normalize_mode];
titleStr = sprintf(['Range Profile Map (HRRP 一维距离历程图)\n', ...
    'Model: %s | BW: %.1f GHz | Res: %.2f cm | %s: %.1f%s | Win: %s | %s'], ...
    modelName, B/1e9, delta_r*100, angleStepLabel, angleStep, char(176), windowType, normStr);
title(titleStr, 'FontSize', 11);

caxis([dyn_range_min, dyn_range_max]);
cb = colorbar;
if strcmp(normalize_mode, 'none')
    cb.Label.String = 'Scattering Intensity (dB)';
else
    cb.Label.String = 'Relative Intensity (dB)';
end
cb.Label.FontSize = 11;

axis tight;
grid on;
set(gca, 'GridAlpha', 0.3, 'LineWidth', 0.5, 'FontSize', 11, 'YDir', 'normal');

%% ========================================================================
%% 7. 图2: 散射场频域热力图 (诊断图)
%%    参考: test.m Figure 1 和 Copy_of_test.m
%% ========================================================================
fprintf('Generating scattering field heatmap (Figure 2)...\n');

figure(2);
clf;
set(gcf, 'Name', 'Scattering Field Spectrum (频域热力图)', ...
         'NumberTitle', 'off', 'Position', [100, 150, 700, 500]);

% 频域散射场幅度 (dB): freq x angle, 转置以便显示
S_dB = 20 * log10(abs(S_complex) + epsilon_dB);  % angle x freq: 181x256, matches imagesc(x=freq,y=angle)

imagesc(freq_array/1e9, angle_axis, S_dB);
colormap('jet');
axis xy;

xlabel('Frequency (GHz)', 'FontSize', 12, 'FontWeight', 'bold');
ylabel(angleLabel, 'FontSize', 12, 'FontWeight', 'bold');
title(sprintf('Scattering Field Spectrum | Model: %s', modelName), ...
       'FontSize', 13, 'FontWeight', 'bold');

cb2 = colorbar;
cb2.Label.String = '|E_s| (dB)';
cb2.Label.FontSize = 11;

set(gca, 'FontSize', 11, 'YDir', 'normal');
grid on;

%% ========================================================================
%% 8. 图3: 指定角度的单帧一维距离像 (诊断图)
%%    参考: yw.m Figure 2
%% ========================================================================
fprintf('Generating single-angle range profile (Figure 3)...\n');

% 选取中间角度作为单帧展示
ref_angle_idx = round(N_angles_total / 2);
if ip > 1 && it == 1
    ref_angle_val = phi_array(ref_angle_idx, 1);
elseif it > 1 && ip == 1
    ref_angle_val = theta_array(1, ref_angle_idx);
else
    ref_angle_val = ref_angle_idx;
end

figure(3);
clf;
set(gcf, 'Name', sprintf('1D Range Profile at angle = %.1f', ref_angle_val), ...
         'NumberTitle', 'off', 'Position', [150, 200, 700, 450]);

plot(range_axis, M_dB(ref_angle_idx, :), 'b-', 'LineWidth', 1.2);
xlabel('Radial Range (m)', 'FontSize', 12, 'FontWeight', 'bold');
ylabel('Scattering Intensity (dB)', 'FontSize', 12, 'FontWeight', 'bold');
% 去掉 angleLabel 中的反斜杠以便在 title 中显示
angleLabelPlain = strrep(strrep(angleLabel, '\', ''), 'phi', '\phi');
angleLabelPlain = strrep(angleLabelPlain, 'theta', '\theta');
title(sprintf('1D Range Profile (一维距离像) at %s = %.1f%s | Model: %s', ...
       angleLabelPlain, ref_angle_val, char(176), modelName), ...
       'FontSize', 13, 'FontWeight', 'bold');

xlim([range_axis(1), range_axis(end)]);
grid on;
set(gca, 'FontSize', 11);

%% ========================================================================
%% 9. 保存历程图图像和数据
%% ========================================================================
fprintf('\nSaving results...\n');

nowStr = datestr(now, 'yyyymmddHHMMSS');

% ---- 9a. 保存各图为 PNG + FIG ----
figFile1 = fullfile('results', ['hrrp_map_' nowStr '.png']);
saveas(1, figFile1);
fprintf('  Figure 1 (HRRP map):    %s\n', figFile1);

figFile2 = fullfile('results', ['scattering_spectrum_' nowStr '.png']);
saveas(2, figFile2);
fprintf('  Figure 2 (spectrum):    %s\n', figFile2);

figFile3 = fullfile('results', ['range_profile_single_' nowStr '.png']);
saveas(3, figFile3);
fprintf('  Figure 3 (1D profile):  %s\n', figFile3);

saveas(1, fullfile('results', ['hrrp_map_' nowStr '.fig']));

% ---- 9b. 保存历程图数据 (.mat) ----
dataFile = fullfile('results', ['range_profile_data_' nowStr '.mat']);
save(dataFile, 'M_dB', 'M_display', 'range_axis', 'angle_axis', ...
    'delta_r_fft', 'N_fft', 'N_angles_total', 'windowType', ...
    'dyn_range_min', 'dyn_range_max', 'zero_pad_factor', ...
    'angleLabel', 'delta_r', 'B', 'c', 'freq_array', 'R_max', '-v7.3');
fprintf('  Data (.mat):            %s\n', dataFile);

% ---- 9c. 导出文本格式的历程图数据 (.dat) ----
txtFile = fullfile('results', ['range_profile_data_' nowStr '.dat']);
fid = fopen(txtFile, 'w');
fprintf(fid, '# Range Profile Map Data (HRRP 一维距离历程图数据)\n');
fprintf(fid, '# Generated: %s\n', nowStr);
fprintf(fid, '# Model: %s\n', modelName);
fprintf(fid, '# Bandwidth: %.2f GHz | Range res: %.4f m\n', B/1e9, delta_r);
fprintf(fid, '# FFT points: %d | Zero-pad: %dx | Window: %s\n', ...
    N_fft, zero_pad_factor, windowType);
fprintf(fid, '# Dyn range: %.0f ~ %.0f dB\n', dyn_range_min, dyn_range_max);
fprintf(fid, '# Format: %d range bins (cols) x %d angles (rows)\n', N_fft, N_angles_total);
fprintf(fid, '# Range axis (m):\n');
fprintf(fid, '%.6f ', range_axis);
fprintf(fid, '\n# Angle axis:\n');

fprintf(fid, '%.3f ', angle_axis);
fprintf(fid, '\n# HRRP Data (dB), rows=angles, cols=range:\n');
for i = 1:N_angles_total
    fprintf(fid, '%.4f ', M_dB(i, :));
    fprintf(fid, '\n');
end
fclose(fid);
fprintf('  Data (.dat):            %s\n', txtFile);

%% ========================================================================
%% 10. 显示摘要
%% ========================================================================
fprintf('\n========================================\n');
fprintf('  Range Profile Map Complete\n');
fprintf('========================================\n');
fprintf('  Model:            %s\n', modelName);
fprintf('  Bandwidth:        %.2f GHz\n', B/1e9);
fprintf('  Range resolution: %.4f m (%d bins)\n', delta_r_fft, N_fft);
fprintf('  Range span:       %.2f m\n', range_axis(end) - range_axis(1));
fprintf('  Angles:           %d (step: %.1f deg)\n', N_angles_total, angleStep);
fprintf('  Window:           %s | Zero-pad: %dx\n', windowType, zero_pad_factor);
fprintf('  Dyn range:        %.0f ~ %.0f dB\n', dyn_range_min, dyn_range_max);
fprintf('  Output files:\n');
fprintf('    Fig1: %s\n', figFile1);
fprintf('    Fig2: %s\n', figFile2);
fprintf('    Fig3: %s\n', figFile3);
fprintf('    MAT:  %s\n', dataFile);
fprintf('========================================\n');
