function param = plotParameters(mode, freq, wave, corr, delstd, pol, ntria, pstart, pstop, delp, tstart, tstop, delt)
    % PLOTPARAMETERS Build a formatted parameter summary string.
    %
    %   Input:
    %       mode   - 'Monostatic' or 'Bistatic'
    %       freq   - frequency (Hz)
    %       wave   - wavelength (m)
    %       corr   - correlation distance (m)
    %       delstd - standard deviation (m)
    %       pol    - polarization string ('TM-z' or 'TE-z')
    %       ntria  - number of triangles
    %       pstart, pstop, delp - phi angles (degrees)
    %       tstart, tstop, delt - theta angles (degrees)
    %   Output:
    %       param - formatted string

    param = sprintf(['    Mode: %s\n', ...
                     '    Radar Frequency (GHz): %.4f\n', ...
                     '    Wavelength (m): %.6f\n', ...
                     '    Correlation distance (m): %.6f\n', ...
                     '    Standard Deviation (m): %.6f\n', ...
                     '    Incident wave polarization: %s\n', ...
                     '    Number of triangles: %d\n', ...
                     '    Start phi angle (degrees): %d\n', ...
                     '    Stop phi angle (degrees): %d\n', ...
                     '    Phi increment step (degrees): %d\n', ...
                     '    Start theta angle (degrees): %d\n', ...
                     '    Stop theta angle (degrees): %d\n', ...
                     '    Theta increment step (degrees): %d\n'], ...
                     mode, freq/1e9, wave, corr, delstd, pol, ntria, ...
                     pstart, pstop, delp, tstart, tstop, delt);
end
